### ISSUE TITLE
help sp

### ISSUE THREAD

**Issue by ByKyTa** [IT-KiLLER/CSGO-Admin-Room-Finder#2]
i can't smx
//// adminroomfinder.sp
//
// adminroomfinder.sp(165) : error 017: undefined symbol "GetOutputActionCount"
// adminroomfinder.sp(168) : error 017: undefined symbol "GetOutputActionParameter"
//
// 2 Errors.
//
// Compilation Time: 0.42 sec

**Comment by IT-KiLLER** [comment]
You need this file. You should put it in the include folder.
https://github.com/SlidyBat/sm-ext-outputinfo/blob/master/addons/sourcemod/scripting/include/outputinfo.inc
